### ISSUE TITLE
Parameters for tekton-git-ssh-secret.yaml and regsecret.yaml files

### ISSUE THREAD

**Issue by akhil97** [sdaschner/tekton-argocd-example#2]
This example for tekton-git-ssh-secret.yaml and regsecret.yaml files what should be mentioned under the data parameter for ssh-privatekey and .dockercfg parameters? The README file is mentioned as base64 data, but I don't understand how to generate it.

_Originally posted by @akhil97 in https://github.com/sdaschner/tekton-argocd-example/issues/1#issuecomment-1111806704_

**Comment by cameronhudson8** [comment]
@akhil97 To base64-encode a file, you can do this:
```
cat ./path/to/file | base64
```

**Comment by akhil97** [comment]
> @akhil97 To base64-encode a file, you can do this:
> 
> ```
> cat ./path/to/file | base64
> ```

**Comment by akhil97** [comment]
For using an ssh secret key for tekton-git-ssh-secret.yaml this is fine. But what should I do for .dockerconfg parameter?

**Comment by sdaschner** [comment]
Hi @akhil97! In general, the same, you can also encode the whole contents of a Docker file (which is in JSON format).

However, an easier way would be to use the `kubectl` cli methods for this, such as:

```
kubectl create secret <secret-type> <name> [extra-options]
```

See [here](https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kubectl/) for an example, as well as for type `docker-registry`:

```
kubectl create secret docker-registry --help
```
